doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
#        types:
#            array: Doctrine\DBAL\Types\ArrayType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        naming_strategy: doctrine.orm.naming_strategy.default
        naming_strategy: doctrine.orm.naming_strategy.underscore
        controller_resolver:
            auto_mapping: false
        mappings:
            App:
                is_bundle: false
#                type: annotation
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
